#!/usr/bin/env python

import os
import time
import lib.command

k = 10
start = time.time()
while True:
    time.sleep(k)
    dur = time.time() - start
    print 'TIME:', dur
    if dur > 20:
        print 'STOPPING!'
        break

with open('cur_id') as f:
    id = f.read()
lib.command.remove_file_line('data/missing_problems', id)
os.system('./scripts/solver_kill')
