#!/usr/bin/env python

import os
import json

with open('status.json') as f:
    j = f.read().split('\n', 1)[1]
    score = json.loads(j)['contestScore']

with open('score', 'w') as f:
    f.write(str(score))

os.system('festival --tts score')
